name: liaqat_store
description: Liaqat Kiryana Store POS System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.3.7
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  
  # State Management
  provider: ^6.1.1
  
  # UI & Utilities
  intl: 0.20.2
  shared_preferences: ^2.2.2
  
  # File Handling
  file_picker: ^5.3.3
  
  # Printing & PDF
  printing: ^5.11.3
  pdf: ^3.10.6

  # For taking photos
  image_picker: ^1.0.7

  # Optional, for opening the file after save
  open_file: ^3.3.0

  # Flutter BLoC
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  
  # Fonts
  fonts:
    - family: NooriNastaleeq
      fonts:
        - asset: assets/fonts/NooriNastaleeq.ttf
  
  # Assets
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lang/
